# Integrity Evolution website configuration
name = 'integrityevolution'
main = "worker.js"
compatibility_date = "2024-01-01"

[env.production]
name = 'integrityevolution-production'
routes = [
  { pattern = "integrityevolution.com/*", zone_id = "7648c2eeea142e37c9288d0b2e03ba45" },
  { pattern = "www.integrityevolution.com/*", zone_id = "7648c2eeea142e37c9288d0b2e03ba45" }
]